### PR TITLE
adds port to titlebar

### PR DESCRIPTION
**Pull request by zhaguanyang**

### CODE REVIEW

**Comment by ButterscotchV** [comment]
CI seems to be broken, the changes look good so I'll merge it anyways

**Comment by ButterscotchV** [comment]
> I meant to get back to this after the last smod release but multiadmin can't be built as a single platform independent binary anymore, so just have to split it into a windows and linux one.

Latest version in the 3.4.X branch uses AOT, CI just needs to be updated, check #260

**Comment by KarlOfDuty** [comment]
Ah ok, I might just not have found the way to do it last time then.

**Comment by zhaguanyang** [comment]
Actually, I didn't expect such a fast response from you guys lol, since the last commit was like 8 months ago.

**Pull request merged**
